# Generated by Django 3.2.13 on 2022-05-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
